# fly.toml app configuration file generated for sync-service-wandering-morning-6267 on 2024-11-06T09:05:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sync-service-wandering-morning-6267'
primary_region = 'lhr'

[build]
[build.args]
GO_VERSION = '1.22'

[env]
PORT = '8080'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[services]]
internal_port = 8080
protocol = "tcp"
min_machines_running = 1
auto_start_machines = false
processes = ['app']

[[services.ports]]
handlers = ["tls"]
port = 443
tls_options = { "alpn" = ["h2"] }
