// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.4
// source: sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Syncer_SetRecord_FullMethodName   = "/sync.Syncer/SetRecord"
	Syncer_ListChanges_FullMethodName = "/sync.Syncer/ListChanges"
)

// SyncerClient is the client API for Syncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncerClient interface {
	SetRecord(ctx context.Context, in *SetRecordRequest, opts ...grpc.CallOption) (*SetRecordReply, error)
	ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesReply, error)
}

type syncerClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncerClient(cc grpc.ClientConnInterface) SyncerClient {
	return &syncerClient{cc}
}

func (c *syncerClient) SetRecord(ctx context.Context, in *SetRecordRequest, opts ...grpc.CallOption) (*SetRecordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRecordReply)
	err := c.cc.Invoke(ctx, Syncer_SetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangesReply)
	err := c.cc.Invoke(ctx, Syncer_ListChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncerServer is the server API for Syncer service.
// All implementations must embed UnimplementedSyncerServer
// for forward compatibility.
type SyncerServer interface {
	SetRecord(context.Context, *SetRecordRequest) (*SetRecordReply, error)
	ListChanges(context.Context, *ListChangesRequest) (*ListChangesReply, error)
	mustEmbedUnimplementedSyncerServer()
}

// UnimplementedSyncerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncerServer struct{}

func (UnimplementedSyncerServer) SetRecord(context.Context, *SetRecordRequest) (*SetRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRecord not implemented")
}
func (UnimplementedSyncerServer) ListChanges(context.Context, *ListChangesRequest) (*ListChangesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChanges not implemented")
}
func (UnimplementedSyncerServer) mustEmbedUnimplementedSyncerServer() {}
func (UnimplementedSyncerServer) testEmbeddedByValue()                {}

// UnsafeSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncerServer will
// result in compilation errors.
type UnsafeSyncerServer interface {
	mustEmbedUnimplementedSyncerServer()
}

func RegisterSyncerServer(s grpc.ServiceRegistrar, srv SyncerServer) {
	// If the following call pancis, it indicates UnimplementedSyncerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Syncer_ServiceDesc, srv)
}

func _Syncer_SetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).SetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncer_SetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).SetRecord(ctx, req.(*SetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_ListChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).ListChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncer_ListChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).ListChanges(ctx, req.(*ListChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Syncer_ServiceDesc is the grpc.ServiceDesc for Syncer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Syncer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.Syncer",
	HandlerType: (*SyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRecord",
			Handler:    _Syncer_SetRecord_Handler,
		},
		{
			MethodName: "ListChanges",
			Handler:    _Syncer_ListChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync.proto",
}
