// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRecordStatus int32

const (
	SetRecordStatus_SUCCESS  SetRecordStatus = 0
	SetRecordStatus_CONFLICT SetRecordStatus = 1
)

// Enum value maps for SetRecordStatus.
var (
	SetRecordStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "CONFLICT",
	}
	SetRecordStatus_value = map[string]int32{
		"SUCCESS":  0,
		"CONFLICT": 1,
	}
)

func (x SetRecordStatus) Enum() *SetRecordStatus {
	p := new(SetRecordStatus)
	*p = x
	return p
}

func (x SetRecordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetRecordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sync_proto_enumTypes[0].Descriptor()
}

func (SetRecordStatus) Type() protoreflect.EnumType {
	return &file_proto_sync_proto_enumTypes[0]
}

func (x SetRecordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetRecordStatus.Descriptor instead.
func (SetRecordStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{0}
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Record) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	RequestTime   uint32                 `protobuf:"varint,2,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRecordRequest) Reset() {
	*x = SetRecordRequest{}
	mi := &file_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecordRequest) ProtoMessage() {}

func (x *SetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecordRequest.ProtoReflect.Descriptor instead.
func (*SetRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SetRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SetRecordRequest) GetRequestTime() uint32 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *SetRecordRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SetRecordRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type SetRecordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SetRecordStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=sync.SetRecordStatus" json:"status,omitempty"`
	NewRevision   uint64                 `protobuf:"varint,2,opt,name=new_revision,json=newRevision,proto3" json:"new_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRecordReply) Reset() {
	*x = SetRecordReply{}
	mi := &file_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRecordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecordReply) ProtoMessage() {}

func (x *SetRecordReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecordReply.ProtoReflect.Descriptor instead.
func (*SetRecordReply) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SetRecordReply) GetStatus() SetRecordStatus {
	if x != nil {
		return x.Status
	}
	return SetRecordStatus_SUCCESS
}

func (x *SetRecordReply) GetNewRevision() uint64 {
	if x != nil {
		return x.NewRevision
	}
	return 0
}

type ListChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceRevision uint64                 `protobuf:"varint,1,opt,name=since_revision,json=sinceRevision,proto3" json:"since_revision,omitempty"`
	RequestTime   uint32                 `protobuf:"varint,2,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesRequest) Reset() {
	*x = ListChangesRequest{}
	mi := &file_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesRequest) ProtoMessage() {}

func (x *ListChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesRequest.ProtoReflect.Descriptor instead.
func (*ListChangesRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ListChangesRequest) GetSinceRevision() uint64 {
	if x != nil {
		return x.SinceRevision
	}
	return 0
}

func (x *ListChangesRequest) GetRequestTime() uint32 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *ListChangesRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ListChangesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*Record              `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesReply) Reset() {
	*x = ListChangesReply{}
	mi := &file_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesReply) ProtoMessage() {}

func (x *ListChangesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesReply.ProtoReflect.Descriptor instead.
func (*ListChangesReply) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ListChangesReply) GetChanges() []*Record {
	if x != nil {
		return x.Changes
	}
	return nil
}

type ListenChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestTime   uint32                 `protobuf:"varint,1,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenChangesRequest) Reset() {
	*x = ListenChangesRequest{}
	mi := &file_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenChangesRequest) ProtoMessage() {}

func (x *ListenChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenChangesRequest.ProtoReflect.Descriptor instead.
func (*ListenChangesRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ListenChangesRequest) GetRequestTime() uint32 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *ListenChangesRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Notification) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type SetLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockName      string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Acquire       bool                   `protobuf:"varint,3,opt,name=acquire,proto3" json:"acquire,omitempty"`
	Exclusive     bool                   `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	TtlSeconds    *uint32                `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"`
	RequestTime   uint32                 `protobuf:"varint,6,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLockRequest) Reset() {
	*x = SetLockRequest{}
	mi := &file_proto_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLockRequest) ProtoMessage() {}

func (x *SetLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLockRequest.ProtoReflect.Descriptor instead.
func (*SetLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{7}
}

func (x *SetLockRequest) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *SetLockRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SetLockRequest) GetAcquire() bool {
	if x != nil {
		return x.Acquire
	}
	return false
}

func (x *SetLockRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *SetLockRequest) GetTtlSeconds() uint32 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *SetLockRequest) GetRequestTime() uint32 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *SetLockRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SetLockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLockReply) Reset() {
	*x = SetLockReply{}
	mi := &file_proto_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLockReply) ProtoMessage() {}

func (x *SetLockReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLockReply.ProtoReflect.Descriptor instead.
func (*SetLockReply) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{8}
}

type GetLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockName      string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	RequestTime   uint32                 `protobuf:"varint,2,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockRequest) Reset() {
	*x = GetLockRequest{}
	mi := &file_proto_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockRequest) ProtoMessage() {}

func (x *GetLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockRequest.ProtoReflect.Descriptor instead.
func (*GetLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{9}
}

func (x *GetLockRequest) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *GetLockRequest) GetRequestTime() uint32 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *GetLockRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type GetLockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockReply) Reset() {
	*x = GetLockReply{}
	mi := &file_proto_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockReply) ProtoMessage() {}

func (x *GetLockReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockReply.ProtoReflect.Descriptor instead.
func (*GetLockReply) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{10}
}

func (x *GetLockReply) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

var File_proto_sync_proto protoreflect.FileDescriptor

const file_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x10proto/sync.proto\x12\x04sync\"o\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xa9\x01\n" +
	"\x10SetRecordRequest\x12$\n" +
	"\x06record\x18\x01 \x01(\v2\f.sync.RecordR\x06record\x12!\n" +
	"\frequest_time\x18\x02 \x01(\rR\vrequestTime\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12 \n" +
	"\tclient_id\x18\x04 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"b\n" +
	"\x0eSetRecordReply\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.sync.SetRecordStatusR\x06status\x12!\n" +
	"\fnew_revision\x18\x02 \x01(\x04R\vnewRevision\"|\n" +
	"\x12ListChangesRequest\x12%\n" +
	"\x0esince_revision\x18\x01 \x01(\x04R\rsinceRevision\x12!\n" +
	"\frequest_time\x18\x02 \x01(\rR\vrequestTime\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\":\n" +
	"\x10ListChangesReply\x12&\n" +
	"\achanges\x18\x01 \x03(\v2\f.sync.RecordR\achanges\"W\n" +
	"\x14ListenChangesRequest\x12!\n" +
	"\frequest_time\x18\x01 \x01(\rR\vrequestTime\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\">\n" +
	"\fNotification\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"\xfd\x01\n" +
	"\x0eSetLockRequest\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aacquire\x18\x03 \x01(\bR\aacquire\x12\x1c\n" +
	"\texclusive\x18\x04 \x01(\bR\texclusive\x12$\n" +
	"\vttl_seconds\x18\x05 \x01(\rH\x00R\n" +
	"ttlSeconds\x88\x01\x01\x12!\n" +
	"\frequest_time\x18\x06 \x01(\rR\vrequestTime\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignatureB\x0e\n" +
	"\f_ttl_seconds\"\x0e\n" +
	"\fSetLockReply\"n\n" +
	"\x0eGetLockRequest\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12!\n" +
	"\frequest_time\x18\x02 \x01(\rR\vrequestTime\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"&\n" +
	"\fGetLockReply\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked*,\n" +
	"\x0fSetRecordStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\f\n" +
	"\bCONFLICT\x10\x012\xb9\x02\n" +
	"\x06Syncer\x12;\n" +
	"\tSetRecord\x12\x16.sync.SetRecordRequest\x1a\x14.sync.SetRecordReply\"\x00\x12A\n" +
	"\vListChanges\x12\x18.sync.ListChangesRequest\x1a\x16.sync.ListChangesReply\"\x00\x12A\n" +
	"\rListenChanges\x12\x1a.sync.ListenChangesRequest\x1a\x12.sync.Notification0\x01\x125\n" +
	"\aSetLock\x12\x14.sync.SetLockRequest\x1a\x12.sync.SetLockReply\"\x00\x125\n" +
	"\aGetLock\x12\x14.sync.GetLockRequest\x1a\x12.sync.GetLockReply\"\x00B\"Z github.com/breez/data-sync/protob\x06proto3"

var (
	file_proto_sync_proto_rawDescOnce sync.Once
	file_proto_sync_proto_rawDescData []byte
)

func file_proto_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_proto_rawDesc), len(file_proto_sync_proto_rawDesc)))
	})
	return file_proto_sync_proto_rawDescData
}

var file_proto_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_sync_proto_goTypes = []any{
	(SetRecordStatus)(0),         // 0: sync.SetRecordStatus
	(*Record)(nil),               // 1: sync.Record
	(*SetRecordRequest)(nil),     // 2: sync.SetRecordRequest
	(*SetRecordReply)(nil),       // 3: sync.SetRecordReply
	(*ListChangesRequest)(nil),   // 4: sync.ListChangesRequest
	(*ListChangesReply)(nil),     // 5: sync.ListChangesReply
	(*ListenChangesRequest)(nil), // 6: sync.ListenChangesRequest
	(*Notification)(nil),         // 7: sync.Notification
	(*SetLockRequest)(nil),       // 8: sync.SetLockRequest
	(*SetLockReply)(nil),         // 9: sync.SetLockReply
	(*GetLockRequest)(nil),       // 10: sync.GetLockRequest
	(*GetLockReply)(nil),         // 11: sync.GetLockReply
}
var file_proto_sync_proto_depIdxs = []int32{
	1,  // 0: sync.SetRecordRequest.record:type_name -> sync.Record
	0,  // 1: sync.SetRecordReply.status:type_name -> sync.SetRecordStatus
	1,  // 2: sync.ListChangesReply.changes:type_name -> sync.Record
	2,  // 3: sync.Syncer.SetRecord:input_type -> sync.SetRecordRequest
	4,  // 4: sync.Syncer.ListChanges:input_type -> sync.ListChangesRequest
	6,  // 5: sync.Syncer.ListenChanges:input_type -> sync.ListenChangesRequest
	8,  // 6: sync.Syncer.SetLock:input_type -> sync.SetLockRequest
	10, // 7: sync.Syncer.GetLock:input_type -> sync.GetLockRequest
	3,  // 8: sync.Syncer.SetRecord:output_type -> sync.SetRecordReply
	5,  // 9: sync.Syncer.ListChanges:output_type -> sync.ListChangesReply
	7,  // 10: sync.Syncer.ListenChanges:output_type -> sync.Notification
	9,  // 11: sync.Syncer.SetLock:output_type -> sync.SetLockReply
	11, // 12: sync.Syncer.GetLock:output_type -> sync.GetLockReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sync_proto_init() }
func file_proto_sync_proto_init() {
	if File_proto_sync_proto != nil {
		return
	}
	file_proto_sync_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_sync_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_sync_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_proto_rawDesc), len(file_proto_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_proto_depIdxs,
		EnumInfos:         file_proto_sync_proto_enumTypes,
		MessageInfos:      file_proto_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_proto = out.File
	file_proto_sync_proto_goTypes = nil
	file_proto_sync_proto_depIdxs = nil
}
