// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.4
// source: sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Syncer_SetRecord_FullMethodName     = "/sync.Syncer/SetRecord"
	Syncer_ListChanges_FullMethodName   = "/sync.Syncer/ListChanges"
	Syncer_ListenChanges_FullMethodName = "/sync.Syncer/ListenChanges"
)

// SyncerClient is the client API for Syncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncerClient interface {
	SetRecord(ctx context.Context, in *SetRecordRequest, opts ...grpc.CallOption) (*SetRecordReply, error)
	ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesReply, error)
	ListenChanges(ctx context.Context, in *ListenChangesRequest, opts ...grpc.CallOption) (Syncer_ListenChangesClient, error)
}

type syncerClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncerClient(cc grpc.ClientConnInterface) SyncerClient {
	return &syncerClient{cc}
}

func (c *syncerClient) SetRecord(ctx context.Context, in *SetRecordRequest, opts ...grpc.CallOption) (*SetRecordReply, error) {
	out := new(SetRecordReply)
	err := c.cc.Invoke(ctx, Syncer_SetRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesReply, error) {
	out := new(ListChangesReply)
	err := c.cc.Invoke(ctx, Syncer_ListChanges_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) ListenChanges(ctx context.Context, in *ListenChangesRequest, opts ...grpc.CallOption) (Syncer_ListenChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Syncer_ServiceDesc.Streams[0], Syncer_ListenChanges_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &syncerListenChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Syncer_ListenChangesClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type syncerListenChangesClient struct {
	grpc.ClientStream
}

func (x *syncerListenChangesClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncerServer is the server API for Syncer service.
// All implementations must embed UnimplementedSyncerServer
// for forward compatibility
type SyncerServer interface {
	SetRecord(context.Context, *SetRecordRequest) (*SetRecordReply, error)
	ListChanges(context.Context, *ListChangesRequest) (*ListChangesReply, error)
	ListenChanges(*ListenChangesRequest, Syncer_ListenChangesServer) error
	mustEmbedUnimplementedSyncerServer()
}

// UnimplementedSyncerServer must be embedded to have forward compatible implementations.
type UnimplementedSyncerServer struct {
}

func (UnimplementedSyncerServer) SetRecord(context.Context, *SetRecordRequest) (*SetRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRecord not implemented")
}
func (UnimplementedSyncerServer) ListChanges(context.Context, *ListChangesRequest) (*ListChangesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChanges not implemented")
}
func (UnimplementedSyncerServer) ListenChanges(*ListenChangesRequest, Syncer_ListenChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListenChanges not implemented")
}
func (UnimplementedSyncerServer) mustEmbedUnimplementedSyncerServer() {}

// UnsafeSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncerServer will
// result in compilation errors.
type UnsafeSyncerServer interface {
	mustEmbedUnimplementedSyncerServer()
}

func RegisterSyncerServer(s grpc.ServiceRegistrar, srv SyncerServer) {
	s.RegisterService(&Syncer_ServiceDesc, srv)
}

func _Syncer_SetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).SetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncer_SetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).SetRecord(ctx, req.(*SetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_ListChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).ListChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncer_ListChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).ListChanges(ctx, req.(*ListChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_ListenChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncerServer).ListenChanges(m, &syncerListenChangesServer{stream})
}

type Syncer_ListenChangesServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type syncerListenChangesServer struct {
	grpc.ServerStream
}

func (x *syncerListenChangesServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

// Syncer_ServiceDesc is the grpc.ServiceDesc for Syncer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Syncer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.Syncer",
	HandlerType: (*SyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRecord",
			Handler:    _Syncer_SetRecord_Handler,
		},
		{
			MethodName: "ListChanges",
			Handler:    _Syncer_ListChanges_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenChanges",
			Handler:       _Syncer_ListenChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sync.proto",
}
